services:
  api:
    build: .
    ports:
      - "7771:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/transfermarkt
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
